version: "3"

services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      - PUID=1000
      - PGID=1000
      - FLATNOTES_AUTH_TYPE=password
      - FLATNOTES_USERNAME=${USERNAME}
      - FLATNOTES_PASSWORD=${PASSWORD}
      - FLATNOTES_SECRET_KEY=${SECRET_KEY}
    volumes:
      - "${PATH_TO_DATA}:/data"
      # Optional. Allows you to save the search index in a different location:
      # - "./index:/data/.flatnotes"
    ports:
      - "8080:8080"
    restart: unless-stopped
