version: '3'
services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: always
    ports:
      - 3124:80
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=${MYSQL_HOST}
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - SYMFONY__ENV__DATABASE_USER=${MYSQL_DATABASE_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=${MAILER_HOST}
      - SYMFONY__ENV__MAILER_USER=${MAILER_USER}
      - SYMFONY__ENV__MAILER_PASSWORD=${MAILER_PASSWORD}
      - SYMFONY__ENV__FROM_EMAIL=${FROM_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=${DOMAIN_NAME}
      - SYMFONY__ENV__SERVER_NAME=${SERVER_NAME}
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    volumes:
      - ~/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - redis
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

