services:
  db:
    image: postgres:15
    volumes:
      - /docker/joplindb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_DB=joplin
  app:
    image: joplin/server:latest
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - MAILER_ENABLED=1
      - MAILER_HOST=${SMTP_HOST}
      - MAILER_PORT=${SMTP_PORT}
      - MAILER_SECURE=1
      - MAILER_AUTH_USER=${SMTP_EMAIL}
      - MAILER_AUTH_PASSWORD=${SMTP_PASSWORD}
      - MAILER_NOREPLY_NAME=${SMTP_REPLY_NAME}
      - MAILER_NOREPLY_EMAIL=${SMTP_EMAIL}

volumes:
  joplindb:

