version: "3"

services:
  navidrome:
    image: deluan/navidrome:0.51.0
    container_name: navidrome
    restart: always
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_ENABLETRANSCODINGCONFIG=true
      - ND_TRANSCODINGCACHESIZE=5000M
      - ND_IMAGECACHESIZE=2000M
      - ND_REVERSEPROXYWHITELIST=${ND_REVERSEPROXYWHITELIST}
      - ND_BASEURL=${ND_BASEURL}
      - ND_ENABLESHARING=${ND_ENABLESHARING}
      - ND_ENABLEGRAVATAR=${ND_ENABLEGRAVATAR}
      - ND_SPOTIFY_ID=${ND_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${ND_SPOTIFY_SECRET}
      - ND_LASTFM_ENABLED=${ND_LASTFM_ENABLED}
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      - ND_LASTFM_LANGUAGE=${ND_LASTFM_LANGUAGE}
    volumes:
      - "${PATH_TO_NAVIDROME_CONFIG}/data:/data"
      - "${PATH_TO_MUSIC}:/music:ro"

