version: "3"

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    volumes:
      - ${NEXTCLOUD_DB}:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nextcloud:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - ${NEXTCLOUD_DATA}:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
