services:
  heyform:
    image: heyform/community-edition:v0.0.13
    restart: always
    volumes:
      - ${HEYFORM_DATA}/assets:/app/static/upload
    depends_on:
      - mongo
      - keydb
    ports:
      - '${HEYFORM_PORT}:8000'
    environment:
      APP_HOMEPAGE_URL: ${APP_URL}
      SESSION_KEY: ${SESSION_KEY}
      SESSION_MAX_AGE: ${SESSION_MAX_AGE}
      FORM_ENCRYPTION_KEY: ${FORM_ENCRYPTION_KEY}
      MONGO_URI: 'mongodb://mongo:27017/heyform'
      VERIFY_USER_EMAIL: true
      SMTP_FROM: ${SMTP_FROM}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_IGNORE_CERT: ${SMTP_IGNORE_CERT}
      UNSPLASH_CLIENT_ID: ${UNSPLASH_CLIENT_ID}
      REDIS_HOST: keydb
      REDIS_PORT: 6379

  mongo:
    image: percona/percona-server-mongodb:4.4
    restart: always
    volumes:
      - ${HEYFORM_DATA}/database:/data/db

  keydb:
    image: eqalpha/keydb:latest
    restart: always
    command: keydb-server --appendonly yes
    volumes:
      - ${HEYFORM_DATA}/keydb:/data

