version: '3'
services:
    collectd-exporter:
        image: prom/collectd-exporter-linux-arm64
        container_name: collectd-exporter
        ports:
            - '9103:9103'
            - '25826:25826/udp'
        command:
            - '--collectd.listen-address=":25826"'
