version: '3.3'

services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    restart: always
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODE=${CODE}
      - BASE_URL=${BASE_URL}
