services:
  meilisearch:
    image: getmeili/meilisearch:v1.12.7
    container_name: meilisearch
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ${MEILI_DATA}:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
      MEILI_LOG_LEVEL: "info"
